apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-no-filter
spec:
  template:
    serviceAccountName: operate-workflow-sa
  eventBusName: codefresh-eventbus
  dependencies:
    - name: test-dep
      eventSourceName: github
      eventName: example
  triggers:
    - template:
        name: github-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: github-
              spec:
                entrypoint: whalesay
                templates:
                  - name: whalesay
                    container:
                      image: docker/whalesay:latest
                      command: [cowsay]
                      args: ["ziv"]
      retryStrategy:
        steps: 3
